{% set name = "CausalEGM" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/CausalEGM-{{ version }}.tar.gz
  sha256: a727290a1f8ddf16820b268d2cadd1f6687f1fd49d7a87b83ad677e379aebc6c

build:
  noarch: python
  entry_points:
    - causalEGM = CausalEGM.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - tensorflow
    - scikit-learn
    - protobuf ==3.20.0
    - pandas
    - python-dateutil

test:
  imports:
    - CausalEGM
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SUwonglab/CausalEGM
  summary: 'CausalEGM: a general causal inference framework by encoding generative modeling'
  license: MIT
  license_file: LICENSE
  doc_url: https://causalegm.readthedocs.io/
  dev_url: https://github.com/SUwonglab/CausalEGM

extra:
  recipe-maintainers:
    - SUwonglab
