{% set name = "CausalEGM" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/CausalEGM-{{ version }}.tar.gz
  sha256: eb2461388ed125d43c1347f9909246408565ea4b07bbe45fd76c69cbc015de4c

build:
  noarch: python
  entry_points:
    - "causalEGM = CausalEGM.cli:main"
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - tensorflow ==2.8.0
    - tensorflow-determinism ==0.3.0
    - scikit-learn
    - pandas
    - python-dateutil

test:
  imports:
    - CausalEGM
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SUwonglab/CausalEGM
  summary: 'CausalEGM: a general causal inference framework by encoding generative modeling'
  license: MIT
  license_file: LICENSE
  doc_url: https://causalegm.readthedocs.io/
  dev_url: https://github.com/SUwonglab/CausalEGM

extra:
  recipe-maintainers:
    - SUwonglab
