{% set name = "CausalEGM" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/CausalEGM-{{ version }}.tar.gz
  sha256: 9be9f02339d7cc3c0decc31171f1efdbdf6964bf2cfa836a6f6fed21455a19b5

build:
  noarch: python
  entry_points:
    - "causalEGM = CausalEGM.cli:main"
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - tensorflow ==2.8.0
    - scikit-learn
    - pandas
    - python-dateutil

test:
  imports:
    - CausalEGM
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SUwonglab/CausalEGM
  summary: 'CausalEGM: a general causal inference framework by encoding generative modeling'
  license: MIT
  license_file: LICENSE
  doc_url: https://causalegm.readthedocs.io/
  dev_url: https://github.com/SUwonglab/CausalEGM

extra:
  recipe-maintainers:
    - SUwonglab
